version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - package-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - package-cache-{{ .Branch }}
          - package-cache
      - run: yarn
      - save_cache:
          key: package-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: package-cache-{{ .Branch }}
          paths:
            - node_modules
      - save_cache:
          key: package-cache
          paths:
            - node_modules
      - run: yarn test
